name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release:
    name: Build and upload release assets
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode version
        run: |
          sudo xcode-select --switch /Applications/Xcode_16.2.app

      - name: Build
        run: |
          swift build -c release --arch arm64 --arch x86_64
          cp ./.build/apple/Products/Release/figma-export ./Release/figma-export
          cp -r ./.build/apple/Products/Release/figma-export_AndroidExport.bundle ./Release/figma-export_AndroidExport.bundle
          cp -r ./.build/apple/Products/Release/figma-export_XcodeExport.bundle ./Release/figma-export_XcodeExport.bundle
          zip -r figma-export.zip Release LICENSE

      - name: "Upload assets to a release"
        run: gh release upload ${{ github.event.release.tag_name }} figma-export.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
